
image:
  registry: docker.io
  repository: vaultwarden/server
  tag: "1.34.1-alpine"
  pullPolicy: IfNotPresent
  pullSecrets: []
  extraSecrets: []
  extraVars: []
  extraVarsCM: ""
  extraVarsSecret: ""

replicas: 1

fullnameOverride: ""

resourceType: ""

commonAnnotations: {}

configMapAnnotations: {}

podAnnotations: {}

commonLabels: {}

podLabels: {}

initContainers: []

sidecars: []

nodeSelector: {}

affinity: {}

tolerations: []

serviceAccount:
  create: true
  name: "vaultwarden-svc"

podSecurityContext:
  {}

securityContext:
  {}

dnsConfig: {}

enableServiceLinks: true


livenessProbe:
  enabled: true
  initialDelaySeconds: 5
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 10
  path: /alive

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3
  path: /alive

startupProbe:
  enabled: false
  initialDelaySeconds: 5
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 10
  path: /alive

resources:
  {}

strategy:
  {}

podDisruptionBudget:
  enabled: false
  minAvailable: 1
  maxUnavailable: null



storage:
  existingVolumeClaim:
    {}

  data:
    {}

  attachments:
    {}

webVaultEnabled: "true"


database:
  type: "default"
  host: ""
  port: ""
  username: ""
  password: ""
  dbName: ""
  uriOverride: ""
  existingSecret: ""
  existingSecretKey: ""
  connectionRetries: 15
  maxConnections: 10

pushNotifications:
  enabled: false
  existingSecret: ""
  installationId:
    value: ""
    existingSecretKey: ""
  installationKey:
    value: ""
    existingSecretKey: ""
  relayUri: "https://push.bitwarden.com"
  identityUri: "https://identity.bitwarden.com"


emergencyNotifReminderSched: "0 3 * * * *"

emergencyRqstTimeoutSched: "0 7 * * * *"

eventCleanupSched: "0 10 0 * * *"

eventsDayRetain: ""

domain: "https://vaultwarden.your-domain.com"

sendsAllowed: "true"

hibpApiKey: ""

orgAttachmentLimit: ""

userAttachmentLimit: ""

userSendLimit: ""

trashAutoDeleteDays: ""

signupsAllowed: true

signupsVerify: "true"

signupDomains: ""

orgEventsEnabled: "false"

orgCreationUsers: ""

invitationsAllowed: true

invitationOrgName: "Vaultwarden"

invitationExpirationHours: "120"

emergencyAccessAllowed: "true"

emailChangeAllowed: "true"

showPassHint: "false"


ipHeader: "X-Real-IP"

iconService: "internal"

iconRedirectCode: "302"

iconBlacklistNonGlobalIps: "true"

experimentalClientFeatureFlags: null

requireDeviceEmail: "false"

extendedLogging: "true"

logTimestampFormat: "%Y-%m-%d %H:%M:%S.%3f"

logging:
  logLevel: ""
  logFile: ""

adminToken:
  existingSecret: ""
  existingSecretKey: ""
  value: "$argon2id$v=19$m=19456,t=2,p=1$Vkx1VkE4RmhDMUhwNm9YVlhPQkVOZk1Yc1duSDdGRVYzd0Y5ZkgwaVg0Yz0$PK+h1ANCbzzmEKaiQfCjWw+hWFaMKvLhG2PjRanH5Kk"

adminRateLimitSeconds: "300"

adminRateLimitMaxBurst: "3"

timeZone: ""


orgGroupsEnabled: "false"

yubico:
  clientId: "112701"
  existingSecret: "yubisecret"
  secretKey:
    existingSecretKey: "YUBI"

duo:
  iKey: ""
  existingSecret: ""
  sKey:
    value: ""
    existingSecretKey: ""
  hostname: ""

smtp:
  existingSecret: ""
  host: ""
  security: "starttls"
  port: 25
  from: ""
  fromName: ""
  username:
    value: ""
    existingSecretKey: ""
  password:
    value: ""
    existingSecretKey: ""
  authMechanism: "Plain"
  acceptInvalidHostnames: "false"
  acceptInvalidCerts: "false"
  debug: false


rocket:
  address: "0.0.0.0"
  port: "8080"
  workers: "10"

service:
  type: "ClusterIP"
  annotations: {}
  labels: {}
  ipFamilyPolicy: "SingleStack"
  sessionAffinity: ""
  sessionAffinityConfig: {}

ingress:
  enabled: true
  class: "ingress-nginx"
  nginxIngressAnnotations: true
  additionalAnnotations: {}
  labels: {}
  tls: true
  hostname: "warden.your-domain.com"
  additionalHostnames: []
  path: "/"
  pathType: "Prefix"
  tlsSecret: ""
  nginxAllowList: ""
  customHeadersConfigMap: {}

