grafana:
    enabled: true    
    ingress:
        enabled: true
        annotations:                                                                                                                           
          kubernetes.io/ingress.class: ingress-nginx    
        hosts:
        - dashboard.your-domain.com
        tls:
         - secretName: your-domain.com
           hosts:
           - dashboard.your-domain.com
