common:
  name: "glance"
  service:
    servicePort: 8080
    containerPort: 8080
  deployment:
    port: 8080
    args:
      - "--config"
      - "/mnt/glance.yml"
  image:
    repository: glanceapp/glance
    tag: v0.8.3
    pullPolicy: IfNotPresent
  configMap:
    enabled: true
    data:
      - name: "config"
        mountPath: "/mnt"
        data:
          - content:
              glance.yml: |
                # Note: I installed this with the Proxmox Helper Script. So this config file is in /opt/glance. If you run with docker their may be multiple configuration files.
                theme:
                  background-color: 0 0 16
                  primary-color: 43 59 81
                  positive-color: 61 66 44
                  negative-color: 6 96 59
                pages:
                  - name: Startpage
                    width: slim
                    hide-desktop-navigation: false
                    center-vertically: true
                    columns:
                
                      - size: small
                        widgets:
                          - type: dns-stats
                            service: pihole
                            url: https://pihole.your-domain.com
                            token: 12345abcdefghijk
                          - type: custom-api
                            title: Immich stats
                            cache: 1d
                            url: https://immich.hopki.net/api/server/statistics
                            headers:
                              x-api-key: 12345abcdefghijk
                              Accept: application/json
                            template: |
                              <div class="flex justify-between text-center">
                                <div>
                                    <div class="color-highlight size-h3">{{ .JSON.Int "photos" | formatNumber }}</div>
                                    <div class="size-h6">PHOTOS</div>
                                </div>
                                <div>
                                    <div class="color-highlight size-h3">{{ .JSON.Int "videos" | formatNumber }}</div>
                                    <div class="size-h6">VIDEOS</div>
                                </div>
                                <div>
                                    <div class="color-highlight size-h3">{{ div (.JSON.Int "usage" | toFloat) 1073741824 | toInt | formatNumber }}GB</div>
                                    <div class="size-h6">USAGE</div>
                                </div>
                              </div>
                
                          - type: repository
                            repository: unixpariah/nixconf
                            pull-requests-limit: 5
                            issues-limit: 3
                            commits-limit: 3
                
                      - size: full
                        widgets:
                          - type: search
                            autofocus: true
                            search-engine: google
                            new-tab: true
                            bangs:
                              - title: YouTube
                                shortcut: "!yt"
                                url: https://www.youtube.com/results?search_query={QUERY}
                              - title: Github
                                shortcut: "!gh"
                                url: https://github.com/search?q={QUERY}&type=repositories
                
                          - type: monitor
                            cache: 1m
                            title: Services
                            sites:
                              - title: Proxmox
                                url: https://proxmox.hopki.net/
                                check-url: https://10.0.0.80:8006
                                allow-insecure: true
                                icon: di:proxmox
                              - title: Nextcloud
                                url: https://cloud.hopki.net/
                                check-url: http://10.0.0.104:11000
                                icon: di:nextcloud
                              - title: Immich
                                url: https://immich.hopki.net/
                                check-url: http://10.0.0.104:2283
                                icon: di:immich
                              - title: Pi-Hole
                                url: https://pihole.your-domain.com/admin
                                check-url: http://pihole-web.pihole-system.svc.cluster.local:80/admin
                                icon: di:pi-hole
                              - title: Vaultwarden
                                url: https://warden.your-domain.com
                                check-url: http://vaultwarden.vaultwarden.svc.cluster.local:80/
                                icon: di:vaultwarden-light
                              - title: NGINX Proxy Manager
                                url: https://proxy.hopki.net/
                                check-url: http://10.0.0.102:81
                                icon: di:nginx
                              - title: Jellyfin
                                url: https://jellyfin.hopki.net/
                                check-url: http://10.0.0.100:8096
                                icon: di:jellyfin
                              - title: Grafana
                                url: https://grafana.your-domain.com
                                check-url: http://grafana.monitoring.svc.cluster.local:3000
                                icon: di:grafana
                
                          - type: monitor
                            cache: 1m
                            title: Web apps
                            sites:
                              - title: Portfolio Site
                                url: https://portfolio.your-domain.com
                                check-url: http://portfolio-client.portfolio.svc.cluster.local:80
                                icon: si:aboutdotme
                              - title: MoxWiki
                                url: https://moxwiki.your-domain.com
                                check-url: http://moxwiki.moxwiki.svc.cluster.local:80
                                icon: si:gitbook
                
                  - name: Home
                    # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
                    # hide-desktop-navigation: true
                    columns:
                      - size: small
                        widgets:
                          - type: calendar
                            first-day-of-week: monday
                
                          - type: rss
                            limit: 10
                            collapse-after: 3
                            cache: 12h
                            feeds:
                              - url: https://omgubuntu.co.uk/feed
                                title: OmgUbuntu
                                limit: 4
                              - url: https://9to5linux.com/feed/atom
                                title: 9to5Linux
                                limit: 4
                
                      - size: full
                        widgets:
                          - type: group
                            widgets:
                              - type: hacker-news
                              - type: lobsters
                
                          - type: videos
                            channels:
                              - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
                              - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
                              - UCsBjURrPoezykLs9EqgamOA # Fireship
                              - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee
                
                          - type: group
                            widgets:
                              - type: reddit
                                subreddit: technology
                                show-thumbnails: true
                              - type: reddit
                                subreddit: selfhosted
                                show-thumbnails: true
                
                      - size: small
                        widgets:
                          - type: weather
                            location: 98664
                            units: imperial
                            hour-format: 12h # alternatively "24h"
                            # Optionally hide the location from being displayed in the widget
                            # hide-location: true
                
                          - type: markets
                            # The link to go to when clicking on the symbol in the UI,
                            # {SYMBOL} will be substituded with the symbol for each market
                            symbol-link-template: https://www.tradingview.com/symbols/{SYMBOL}/news
                            markets:
                              - symbol: LTC-USD
                                name: Litecoin
                              - symbol: XRP-USD
                                name: Ripple
                              - symbol: AAPL
                                name: Apple
                              - symbol: MSFT
                                name: Microsoft
                
                          - type: releases
                            cache: 1d
                            # Without authentication the Github API allows for up to 60 requests per hour. You can create a
                            # read-only token from your Github account settings and use it here to increase the limit.
                            # token: ...
                            repositories:
                              - glanceapp/glance
                              - unixpariah/nixconf
                              - immich-app/immich
                
  startupProbeEnabled: false
  startupProbe: {}
  readinessProbeEnabled: false
  readinessProbe: {}
  livenessProbeEnabled: false
  livenessProbe: {}
  persistence:
    enabled: true
    volumes: []
  ingress:
    enabled: true
    hostName: glance.your-domain.com
    ingressClassName: ""
    extraLabels: {}
    tls:
      enabled: true
      secretName: glance
    annotations:
      {}
      # cert-manager.io/cluster-issuer: cloudflare
