_:
{
  services.k3s.manifests."metallb-configmap".content = [
    {
      apiVersion = "v1";
      kind = "ConfigMap";
      metadata = {
        name = "metallb-excludel2";
        namespace = "metallb-system";
        labels = {
          "app.kubernetes.io/name" = "metallb";
          "app.kubernetes.io/instance" = "metallb";
          "app.kubernetes.io/version" = "v0.15.2";
        };
      };
      data = {
        "excludel2.yaml" =
          "announcedInterfacesToExclude:\n- ^docker.*\n- ^cbr.*\n- ^dummy.*\n- ^virbr.*\n- ^lxcbr.*\n- ^veth.*\n- ^lo$\n- ^cali.*\n- ^tunl.*\n- ^flannel.*\n- ^kube-ipvs.*\n- ^cni.*\n- ^nodelocaldns.*";
      };
    }
    {
      apiVersion = "v1";
      kind = "ConfigMap";
      metadata = {
        name = "metallb-frr-startup";
        namespace = "metallb-system";
        labels = {
          "app.kubernetes.io/name" = "metallb";
          "app.kubernetes.io/instance" = "metallb";
          "app.kubernetes.io/version" = "v0.15.2";
          "app.kubernetes.io/component" = "speaker";
        };
      };
      data = {
        daemons = "# This file tells the frr package which daemons to start.\n#\n# Sample configurations for these daemons can be found in\n# /usr/share/doc/frr/examples/.\n#\n# ATTENTION:\n#\n# When activating a daemon for the first time, a config file, even if it is\n# empty, has to be present *and* be owned by the user and group \"frr\", else\n# the daemon will not be started by /etc/init.d/frr. The permissions should\n# be u=rw,g=r,o=.\n# When using \"vtysh\" such a config file is also needed. It should be owned by\n# group \"frrvty\" and set to ug=rw,o= though. Check /etc/pam.d/frr, too.\n#\n# The watchfrr and zebra daemons are always started.\n#\nbgpd=yes\nospfd=no\nospf6d=no\nripd=no\nripngd=no\nisisd=no\npimd=no\nldpd=no\nnhrpd=no\neigrpd=no\nbabeld=no\nsharpd=no\npbrd=no\nbfdd=yes\nfabricd=no\nvrrpd=no\n\n#\n# If this option is set the /etc/init.d/frr script automatically loads\n# the config via \"vtysh -b\" when the servers are started.\n# Check /etc/pam.d/frr if you intend to use \"vtysh\"!\n#\nvtysh_enable=yes\nzebra_options=\"  -A 127.0.0.1 -s 90000000 --limit-fds 100000\"\nbgpd_options=\"   -A 127.0.0.1 -p 0 --limit-fds 100000\"\nospfd_options=\"  -A 127.0.0.1\"\nospf6d_options=\" -A ::1\"\nripd_options=\"   -A 127.0.0.1\"\nripngd_options=\" -A ::1\"\nisisd_options=\"  -A 127.0.0.1\"\npimd_options=\"   -A 127.0.0.1\"\nldpd_options=\"   -A 127.0.0.1\"\nnhrpd_options=\"  -A 127.0.0.1\"\neigrpd_options=\" -A 127.0.0.1\"\nbabeld_options=\" -A 127.0.0.1\"\nsharpd_options=\" -A 127.0.0.1\"\npbrd_options=\"   -A 127.0.0.1\"\nstaticd_options=\"-A 127.0.0.1 --limit-fds 100000\"\nbfdd_options=\"   -A 127.0.0.1 --limit-fds 100000\"\nfabricd_options=\"-A 127.0.0.1\"\nvrrpd_options=\"  -A 127.0.0.1\"\n\n# configuration profile\n#\n#frr_profile=\"traditional\"\n#frr_profile=\"datacenter\"\n\n#\n# This is the maximum number of FD's that will be available.\n# Upon startup this is read by the control files and ulimit\n# is called. Uncomment and use a reasonable value for your\n# setup if you are expecting a large number of peers in\n# say BGP.\n#MAX_FDS=1024\n\n# The list of daemons to watch is automatically generated by the init script.\n#watchfrr_options=\"\"\n\n# for debugging purposes, you can specify a \"wrap\" command to start instead\n# of starting the daemon directly, e.g. to use valgrind on ospfd:\n#   ospfd_wrap=\"/usr/bin/valgrind\"\n# or you can use \"all_wrap\" for all daemons, e.g. to use perf record:\n#   all_wrap=\"/usr/bin/perf record --call-graph -\"\n# the normal daemon command is added to this at the end.\n";
        "vtysh.conf" = "service integrated-vtysh-config\n";
        "frr.conf" =
          "! This file gets overriden the first time the speaker renders a config.\n! So anything configured here is only temporary.\nfrr version 8.0\nfrr defaults traditional\nhostname Router\nline vty\nlog file /etc/frr/frr.log informational";
      };
    }
  ];
}
