forgejo_api_token: ENC[AES256_GCM,data:Y/cIOBUnXfrQLecEAscT3NR0bAVugE0SyIVpbGfJ4i3WFsVpfv+lKw==,iv:DzI8ryzc830xWkr9wZZq8xtv71LzW/2BE8HK6erONVU=,tag:mSIoNCUFMSc5+KpiOZ6eEA==,type:str]
sops:
    hc_vault:
        - vault_address: https://vault.r0chd.pl
          engine_path: transit
          key_name: fi-sops
          created_at: "2026-02-04T00:47:41Z"
          enc: vault:v1:8AGa5Y8SlpYVL6t72kiYWdST9AwwHB9HlMsYlPDmcAvARa3gyh6TB85CL6TRXLMonmXGrJTohgrPwi8f
    age:
        - recipient: age1e0mcqrfny3lkmnv6qgxel3p035frwm0kdf8cexgtktpkzmvaugrqw2u4ug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRzMrT211NTN6cXZrb0k0
            VElMaGZpQzliYzR4TUJyNk5vVXY3MUMrNGdZCmtBTkhFaTlQdlFlYmx0MjQ5WnRZ
            S3BoMHp1ZThQMzQ3SFI4bGYydVppYmMKLS0tIG83bUQxeU5EcU1DM3pwRk0yTmJl
            aTdZTndpN0RvQ3hia0ZiV0Nkbi8rancKlZQ6bFlJVtwZds2PzcyF3xfuXMZFP9zg
            FkT0qEQ8XDGS2Oh5F1l4A3BM+PmpUnv7Xjf9+dlieTqKox8nnhLzFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T01:40:49Z"
    mac: ENC[AES256_GCM,data:8lhGWmxiap4ORAAS4yFWkZwmkyvqoM8OEGY/4QLmc35FpQnzEexZgrKKCsXVs+tY0bZIQ1Av63CKGPI2G/nGhtm9dEERkPLEZ5f9wVzS93cgsh8UvjLEW0KYU6o4RmT4m4+eRfEjgJ5jqx902mmF2d6VdsZ16gjIiMP4PMHr44A=,iv:KVXYTeExhqGLJIGLvRlqXXv2v4veN0Fb2r8LdsyUAj0=,tag:uJz2FCTLrZc/U1bWQllPLQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
