minio:
    access_key_id: ENC[AES256_GCM,data:3alFKPRLFPLkzg==,iv:ViHy4Moz4xNB0L5Ck0X/oJjC6Q9leN9oMCdNsUsoSE4=,tag:cY/zYVpggMS1bV8t/ZgDTg==,type:str]
    secret_access_key: ENC[AES256_GCM,data:kwcY0R75KHDb5tVZ52+Uh8LbrN2TwQdFtK6Qj43TGkrIU3HNNRniuqIuzA==,iv:GEKMK5pFwx/XaoFdXydeq16A0sXSu3iJj0tLFrszhcE=,tag:g3jb5YtyPMbh7j/poz1j6Q==,type:str]
sops:
    age:
        - recipient: age19kl6jcwqxwkv060nvmjgq8rze8dfjflc0un0evtwgvjqd6qa7p0s0mj8qr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMHVSakMvdUJ5MUJIS1dB
            amJjNDlkT0tiTkd6a1dkQXlkL2hZUmh0Mmd3Ci90Y0h3TElWT01mOGRQTnY1eVVt
            bU9nVFdzcG1kZGI0K2dLbkhWcFU1ZTAKLS0tIDNaRWNQbmdWZjNkblZ6dXVDWHVD
            SnY3WlR1T0x4bGkxQ3N4RDhSZUE1Z0UKG1Hfoc3hn2QlaJoe3xgpvmxsO+S+hwJz
            i8v0FaKZcpw5+biibleFGGlyT+N8FDJvv716+4o383mBaSpxDUXsFw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fsfxy6x7kh8m0usfmj52n22fhfw5859dks4jsj9pkz6pmk3wzvuqc8ghq9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbnpNTm0wa1FuSDVNTVh5
            VmoyVGVySll4L2Zuc3lQYW1DZXdmYk1GKzNvCkRUV1orNnpRNGJuRnNzbXJETFA5
            KzIzOGlrcmluaEx0LzBFc0Q2UzFLMGMKLS0tIEpzWEVaaExoR2oyOHNqeWcyckQr
            czBjdHFiRGRGRHVGd0N1ODNIOVgwekEKZLC3sKh8sKN/dIoxHv7Uu8tETDTxbAf6
            2TXvz67cQIT3Yov7Tryq0ohk+B8UiYt8qkM8/0JbHpxtMq2AC6zIXQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nz3zrfup532rp0rt638wssnez4frpw8lnv7655svn0al0e0vevcqcpc7my
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWjdjdTl2RWpZSFpzR3BL
            TzdwVENYaURVVXRFOWNIVnFyUGNjT1h6a2xjCmVPT2FRSFhUdkZpNHBNa3gyb3VJ
            V3ZwNXRlZ3hoMi8zY3JhMFQ3emFzM1EKLS0tIDd0TWl6cWZsNHhYQ3p0U1JKeWFr
            ZEVuUzVlTGZJaWdTTnM5UGc5TUxXMTAKeRNIgkz1s8KfSLBTGAJj/NTR/vX/tb4U
            9nn5brJCoeT+ymI9R6N4tMAahI8cMZEebGxEIz3DA4gDRF0Yv4vFyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T21:18:05Z"
    mac: ENC[AES256_GCM,data:QmardQQiFjy5UwPSphxi49FVgH3kt0LG2jbZt18NpeSxzxkUFeM+voiSIno/PsVOwHG3MtgEgnNxZtndbXgmgVeZBB0ICKAOCf4pr7xGkU6ublOQQ8keA24/CC4t3rE0/KgJcZk4n9Z8IounH8WOfmfzTcYhsnM70VfHQ/PUFqo=,iv:bVzqeNF3CpGuXwcVWV5yQaaJygDlTIUptmFaiNsV13M=,tag:rsL26Tbk4KwNHL30WDkJGQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
