keys:
  - &unixpariah age1dg2slzrgp3dczzxwmz99236nrt7aydxc43x6cmk2eg4rh460mg0q9dk536
  - &root age1tp6dlk5urkw4tahmkcv7dpr57hwxrmhefe7de42ak3h9ckrcgc7q0svyzv
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
        - *unixpariah
        - *root
