DNS1:
  192.168.30.1
persistentVolumeClaim:
  enabled: true
  storageClass: "openebs-hostpath"
ingress:
  enabled: true
  hosts:
    - "pihole.home"
serviceWeb:
  loadBalancerIP: 192.168.30.103
  annotations:
    metallb.unfiverse.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
serviceDns:
  loadBalancerIP: 192.168.30.102
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
replicaCount: 1
admin:
  enabled: true
  existingSecret: "pihole-password"
  passwordKey: "password"
  annotaions:
