keys:
  - &root age1xmdepvl32zaml4d23eyrq9mg97h57mx0z567a7exk4ch9e6z5sjq4gnj05
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
        - *root
        hc_vault:
          - "https://vault.r0chd.pl/v1/transit/keys/fi-sops"
