zfsNode:
  driverRegistrar:
    image:
      registry: registry.k8s.io/
      repository: sig-storage/csi-node-driver-registrar
      tag: v2.8.0

  zfsPlugin:
    image:
      registry: openebs/
      repository: zfs-driver
      tag: 2.5.0

zfsController:
  resizer:
    image:
      registry: registry.k8s.io/
      repository: sig-storage/csi-resizer
      tag: v1.8.0
      
  snapshotter:
    image:
      registry: registry.k8s.io/
      repository: sig-storage/csi-snapshotter
      tag: v6.2.2
      
  snapshotController:
    image:
      registry: registry.k8s.io/
      repository: sig-storage/snapshot-controller
      tag: v6.2.2

  provisioner:
    image:
      registry: registry.k8s.io/
      repository: sig-storage/csi-provisioner
      tag: v3.5.0

  zfsPlugin:
    image:
      registry: openebs/
      repository: zfs-driver
      tag: 2.5.0

analytics:
  enabled: false
