repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus-operator-crds
    namespace: monitoring
    createNamespace: true
    chart: prometheus-community/prometheus-operator-crds
