helmfiles:
  - path: global/repositories.yaml
  - path: components/metallb/helmfile.yaml
  - path: components/ingress-nginx/helmfile.yaml
  - path: components/flannel/helmfile.yaml

#releases:
  #- name: prometheus
    #namespace: monitoring
    #createNamespace: true
    #chart: prometheus-community/kube-prometheus-stack
    #values:
      #- ./values.yaml
      #
