garage:
    admin-token: ENC[AES256_GCM,data:A8rM6xinoIwmZRZUTPAmaLZB3yzdMs01VpeAT5QtZT9i/X3oEZTnAKWAfe4=,iv:zzvIUEq8P3+3J5ehPWRjt2GvLMI9QCu5hV0z8wplzRk=,tag:Ssui2IOuEcBpSJhyuR3WOQ==,type:str]
sops:
    hc_vault:
        - vault_address: https://vault.kms.r0chd.pl
          engine_path: transit
          key_name: fi-sops
          created_at: "2025-11-11T19:17:15Z"
          enc: vault:v1:2cGwkFiCKpacDdvkyP4aANv244yXh5YpXIGy7FP9OBLKeQ+bjmfcN0R+mexBxgNOXQN46ROeMP9OYflm
    age:
        - recipient: age1e0mcqrfny3lkmnv6qgxel3p035frwm0kdf8cexgtktpkzmvaugrqw2u4ug
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRVZzejVKYllsYVh2ZmMz
            TytrVnZIWGY0ZGdtMUZXUTUvdUc4RXErc2lBClRuU0NwdHJuSjVoZmlqMWpFNmMw
            SWc3RUw1YWtPdklqNVpabVNtcCs4d2MKLS0tIHRWR0lrU3BwQ01VS1k1ODFwQW9U
            VmhmSjJvVE95N1NoS21mZzJkVkx5NHMK5oON8tPVtnaKtqkXEWr0fNu1mw4/rR0T
            BFxsVJ6T8VOzbYVhUmGsZ2LTLlg5lWAb//sn2y7aj/yg1ICU6o/X9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-08T14:40:14Z"
    mac: ENC[AES256_GCM,data:1YDeRFainXmLbRWnFoJXLNqWPwNCdCBo/y289ErjcHb4sHxSs49Qrarg3doFzzFryFh0ZfyLisO+D+W5HvoQa+qvFhuNtqxKUERyVG9Km2tCwIcwIcIHKuC063QVJJJBIwc+dWIgPPtFP4sOTMoPw21Zxx490NDzY8yBX5Dhhkg=,iv:ODjjZIRQfFNqaaH4iR8vK+fuP8SEO/wzOtsqegbI0uU=,tag:rHcJdLCWuBd3Q/7t0bDFNQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
