controller:
  ingressClassResource:
    name: ingress-nginx
    enabled: true
    default: true
    controllerValue: "k8s.io/ingress.nginx"
    parameters: {}
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
ingressClass: ingress-nginx

