helmfiles:
  - path: global/repositories.yaml
  - path: components/metallb/helmfile.yaml
  - path: components/ingress-nginx/helmfile.yaml
  - path: components/flannel/helmfile.yaml
  - path: components/longhorn/helmfile.yaml
  - path: components/prometheus/helmfile.yaml
