keys:
  - &os1 age1dg6794mp72429yf8h2aa55rusn4t2jqjkurnkc4kcuvr2f3cms0sehe5ej
  - &root age1ld78yew4eu6phswz6daznkm24c97dtln30wg7nxw8ysexvj9wqksdkwexq
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
        - *os1
        - *root
