keys:
  - &laptop age1lpg2ahjc4ashmfc27f03sggwr7fy2x6lfemvsvutl49cgsdwvsysw7x4th
  - &laptop-huawei age14tnez5sz8j37864lfvrckslrn6sl34asy0m7cglpyy7rwaf27g3qhxl90l
  - &server-0 age1xn5a8wuwt3c7r5njtlzwfwuvryanrtr5uvcgzazwh77pap0vu38qsm24lg
  - &agent-0 age1npphzfaarxvv2flkmdkm777gafuhvmsh38020432ju9v0aznh55sd0ce3s
  - &fi-srv-1 age1e0mcqrfny3lkmnv6qgxel3p035frwm0kdf8cexgtktpkzmvaugrqw2u4ug
  - &kms age1suyudkl2xlle4uu6e0ld7lughpr5ekg5vxh2ef0kv5wga5j0f3jscpxtz2
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *laptop
          - *laptop-huawei
          - *server-0
          - *agent-0
          - *fi-srv-1
          - *kms
