keys:
  - &unixpariah age1fsfxy6x7kh8m0usfmj52n22fhfw5859dks4jsj9pkz6pmk3wzvuqc8ghq9
  - &root age1lpg2ahjc4ashmfc27f03sggwr7fy2x6lfemvsvutl49cgsdwvsysw7x4th
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
        - *unixpariah
        - *root
