repositories:
  - name: openebs
    url: https://openebs.github.io/charts

releases:
    - name: openebs
      namespace: openebs-system
      createNamespace: true
      chart: openebs/openebs
      values:
        - values/openebs-values.yaml

    #- name: openebs-zfs-localpv
      #namespace: openebs-system
      #chart: openebs/zfs-localpv
      #needs:
        #- openebs-system/openebs
      #values:
        #- values/zfs-localpv-values.yaml
