apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: cert-manager
spec:
  secretName: wildcard-tls-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "*.your-domain.com"
  dnsNames:
    - "*.your-domain.com"
    - "your-domain.com"
