apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - cluster-issuer.yaml
  - certificate.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: Kustomize
